window.MEP_REPLACEMENT_MASTER = [
  {
    "sl": 1,
    "replace_id": "18972",
    "replace_name": "Muniya Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "02-Oct-2026",
    "new_sl": "1",
    "new_id": "19080",
    "new_name": "Hafsa Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "30-Sep-2026",
    "remarks": "Resigned / ইস্তফা"
  },
  {
    "sl": 2,
    "replace_id": "17848",
    "replace_name": "Bithi Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "30-Sep-2026",
    "new_sl": "2",
    "new_id": "19079",
    "new_name": "Hasi Akter",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "30-Sep-2026",
    "remarks": "Resigned / ইস্তফা"
  },
  {
    "sl": 3,
    "replace_id": "18459",
    "replace_name": "Kamrul Islam",
    "replace_designation": "Helper",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "02-Oct-2026",
    "new_sl": "3",
    "new_id": "19077",
    "new_name": "Md.Saimun Islam Rahat",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "30-Sep-2026",
    "remarks": "Resigned / ইস্তফা"
  },
  {
    "sl": 4,
    "replace_id": "18674",
    "replace_name": "Halima Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "26-Sep-2026",
    "new_sl": "4",
    "new_id": "19056",
    "new_name": "Aklima Akter",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "26-Sep-2026",
    "remarks": "Resigned / ইস্তফা"
  },
  {
    "sl": 5,
    "replace_id": "18973",
    "replace_name": "Nurjahan Akter Rupa",
    "replace_designation": "Helper",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "7-Sep-26",
    "new_sl": "5",
    "new_id": "19035",
    "new_name": "Susmita Howlader",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "16-Sep-26",
    "remarks": ""
  },
  {
    "sl": 6,
    "replace_id": "18866",
    "replace_name": "Md. Hriday",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "26-Aug-26",
    "new_sl": "6",
    "new_id": "19034",
    "new_name": "Antor Halder",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "16-Sep-26",
    "remarks": ""
  },
  {
    "sl": 7,
    "replace_id": "18861",
    "replace_name": "Kulsum Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "26-Aug-26",
    "new_sl": "7",
    "new_id": "19021",
    "new_name": "Moni Akter",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "14-Sep-26",
    "remarks": ""
  },
  {
    "sl": 8,
    "replace_id": "18971",
    "replace_name": "Sadia Islam",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "7-Sep-26",
    "new_sl": "8",
    "new_id": "19020",
    "new_name": "Jorna Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "14-Sep-26",
    "remarks": ""
  },
  {
    "sl": 9,
    "replace_id": "18837",
    "replace_name": "Al-Amin",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "19-Aug-26",
    "new_sl": "9",
    "new_id": "19000",
    "new_name": "Md.Rayhan",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "12-Sep-26",
    "remarks": ""
  },
  {
    "sl": 10,
    "replace_id": "18254",
    "replace_name": "Sarmin Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "17-Jun-26",
    "new_sl": "10",
    "new_id": "18973",
    "new_name": "Nurjahan Akter Rupa",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "7-Sep-26",
    "remarks": ""
  },
  {
    "sl": 11,
    "replace_id": "18676",
    "replace_name": "Jesmin Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "1-Aug-26",
    "new_sl": "11",
    "new_id": "18972",
    "new_name": "Muniya Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "7-Sep-26",
    "remarks": ""
  },
  {
    "sl": 12,
    "replace_id": "18330",
    "replace_name": "Sarmin Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "26-Jun-26",
    "new_sl": "12",
    "new_id": "18971",
    "new_name": "Sadia Islam",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "7-Sep-26",
    "remarks": ""
  },
  {
    "sl": 13,
    "replace_id": "18608",
    "replace_name": "Robiul Islam",
    "replace_designation": "Delivery Assistant",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "1-Aug-26",
    "new_sl": "13",
    "new_id": "18970",
    "new_name": "Tusher Sheikh",
    "new_designation": "Delivery Assistant",
    "new_section": "Fan Assemble Line",
    "new_doj": "7-Sep-26",
    "remarks": ""
  },
  {
    "sl": 14,
    "replace_id": "17355",
    "replace_name": "Bijan Kumar Das",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "18-Oct-25",
    "new_sl": "14",
    "new_id": "18869",
    "new_name": "Mehedi Hassan",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "26-Aug-26",
    "remarks": ""
  },
  {
    "sl": 15,
    "replace_id": "18315",
    "replace_name": "Rabbi Howlader",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "27-Jun-26",
    "new_sl": "15",
    "new_id": "18868",
    "new_name": "Riazul Islam shaon",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "26-Aug-26",
    "remarks": ""
  },
  {
    "sl": 16,
    "replace_id": "18575",
    "replace_name": "Hasan Mridha",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "26-Jul-26",
    "new_sl": "16",
    "new_id": "18867",
    "new_name": "Muhid Hasib",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "26-Aug-26",
    "remarks": ""
  },
  {
    "sl": 17,
    "replace_id": "18510",
    "replace_name": "Sakil Rahaman",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "15-Jul-26",
    "new_sl": "17",
    "new_id": "18866",
    "new_name": "Md. Hriday",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "26-Aug-26",
    "remarks": ""
  },
  {
    "sl": 18,
    "replace_id": "18129",
    "replace_name": "Anjona Rani",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "6-Jun-26",
    "new_sl": "18",
    "new_id": "18865",
    "new_name": "Nur Hossen",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "26-Aug-26",
    "remarks": ""
  },
  {
    "sl": 19,
    "replace_id": "18434",
    "replace_name": "Rahaman akhon",
    "replace_designation": "Helper",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "8-Jul-26",
    "new_sl": "19",
    "new_id": "18864",
    "new_name": "Lamiya Akter",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "26-Aug-26",
    "remarks": ""
  },
  {
    "sl": 20,
    "replace_id": "18493",
    "replace_name": "Sumi Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "12-Jul-26",
    "new_sl": "20",
    "new_id": "18863",
    "new_name": "Sumona Akter",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "26-Aug-26",
    "remarks": ""
  },
  {
    "sl": 21,
    "replace_id": "18756",
    "replace_name": "Nasima Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "10-Aug-26",
    "new_sl": "21",
    "new_id": "18862",
    "new_name": "Reshma Akter",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "26-Aug-26",
    "remarks": ""
  },
  {
    "sl": 22,
    "replace_id": "18836",
    "replace_name": "Nipa Islam jakia",
    "replace_designation": "Helper",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "19-Aug-26",
    "new_sl": "22",
    "new_id": "18861",
    "new_name": "Kulsum Akter",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "26-Aug-26",
    "remarks": ""
  },
  {
    "sl": 23,
    "replace_id": "18390",
    "replace_name": "Asraful Islam",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "2-Jul-26",
    "new_sl": "23",
    "new_id": "18839",
    "new_name": "Rita mony khatun",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "19-Aug-26",
    "remarks": ""
  },
  {
    "sl": 24,
    "replace_id": "18435",
    "replace_name": "Tamim Khan",
    "replace_designation": "Helper",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "8-Jul-26",
    "new_sl": "24",
    "new_id": "18838",
    "new_name": "Md.Saidul Islam",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "19-Aug-26",
    "remarks": ""
  },
  {
    "sl": 25,
    "replace_id": "18230",
    "replace_name": "Rabiul Khandoker",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "14-Jun-26",
    "new_sl": "25",
    "new_id": "18837",
    "new_name": "Al-Amin",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "19-Aug-26",
    "remarks": ""
  },
  {
    "sl": 26,
    "replace_id": "18436",
    "replace_name": "Mitu Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "7-Jul-26",
    "new_sl": "26",
    "new_id": "18836",
    "new_name": "Nipa Islam jakia",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "19-Aug-26",
    "remarks": ""
  },
  {
    "sl": 27,
    "replace_id": "18443",
    "replace_name": "Asia Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "7-Jul-26",
    "new_sl": "27",
    "new_id": "18835",
    "new_name": "Tanzila Akter",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "19-Aug-26",
    "remarks": ""
  },
  {
    "sl": 28,
    "replace_id": "17917",
    "replace_name": "Jannatul Islam",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "9-Apr-26",
    "new_sl": "28",
    "new_id": "18817",
    "new_name": "Lamiya Akter",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "18-Aug-26",
    "remarks": ""
  },
  {
    "sl": 29,
    "replace_id": "18161",
    "replace_name": "Tulsi Rani",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "8-Jun-26",
    "new_sl": "29",
    "new_id": "18816",
    "new_name": "Sabina Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "18-Aug-26",
    "remarks": ""
  },
  {
    "sl": 30,
    "replace_id": "18310",
    "replace_name": "Md. Rasel",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "27-Jun-26",
    "new_sl": "30",
    "new_id": "18807",
    "new_name": "Eva Akter",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "18-Aug-26",
    "remarks": ""
  },
  {
    "sl": 31,
    "replace_id": "18656",
    "replace_name": "Semul Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "1-Aug-26",
    "new_sl": "31",
    "new_id": "18806",
    "new_name": "Lucky Begum",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "18-Aug-26",
    "remarks": ""
  },
  {
    "sl": 32,
    "replace_id": "18119",
    "replace_name": "Harun or Rasid",
    "replace_designation": "Operator",
    "replace_section": "Fan Lathe",
    "replace_doj": "3-Jun-26",
    "new_sl": "32",
    "new_id": "18774",
    "new_name": "Abu Taher",
    "new_designation": "Operator",
    "new_section": "Fan Lathe",
    "new_doj": "15-Aug-26",
    "remarks": ""
  },
  {
    "sl": 33,
    "replace_id": "14222",
    "replace_name": "Tanjila",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "10-Jul-23",
    "new_sl": "33",
    "new_id": "18785",
    "new_name": "Rupa Akter",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "13-Aug-26",
    "remarks": ""
  },
  {
    "sl": 34,
    "replace_id": "17558",
    "replace_name": "Md. Kalam Howlader",
    "replace_designation": "Operator",
    "replace_section": "Fan Lathe",
    "replace_doj": "3-Dec-25",
    "new_sl": "34",
    "new_id": "18772",
    "new_name": "MD.Sakil",
    "new_designation": "Operator",
    "new_section": "Fan Lathe",
    "new_doj": "11-Aug-26",
    "remarks": ""
  },
  {
    "sl": 35,
    "replace_id": "18030",
    "replace_name": "Porosh",
    "replace_designation": "Helper",
    "replace_section": "Fan Rojonigondha",
    "replace_doj": "4-May-26",
    "new_sl": "35",
    "new_id": "18771",
    "new_name": "Rakib",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "11-Aug-26",
    "remarks": ""
  },
  {
    "sl": 36,
    "replace_id": "18281",
    "replace_name": "Sathi Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Rojonigondha",
    "replace_doj": "20-Jun-26",
    "new_sl": "36",
    "new_id": "18770",
    "new_name": "Tammana Akter",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "11-Aug-26",
    "remarks": ""
  },
  {
    "sl": 37,
    "replace_id": "18375",
    "replace_name": "Sumiya Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "1-Jul-26",
    "new_sl": "37",
    "new_id": "18756",
    "new_name": "Nasima Begum",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "10-Aug-26",
    "remarks": ""
  },
  {
    "sl": 38,
    "replace_id": "17336",
    "replace_name": "Sarmin",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "11-Oct-25",
    "new_sl": "38",
    "new_id": "18749",
    "new_name": "Khaleda Begum",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "10-Aug-26",
    "remarks": ""
  },
  {
    "sl": 39,
    "replace_id": "18607",
    "replace_name": "Sumi Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "26-Jul-26",
    "new_sl": "39",
    "new_id": "18748",
    "new_name": "Dipa Rani Sil",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "10-Aug-26",
    "remarks": ""
  },
  {
    "sl": 40,
    "replace_id": "18095",
    "replace_name": "Eti Halder",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "13-May-26",
    "new_sl": "40",
    "new_id": "18694",
    "new_name": "Baishakhi Halder",
    "new_designation": "Helper",
    "new_section": "Fan Dimmer and Blade",
    "new_doj": "2-Aug-26",
    "remarks": ""
  },
  {
    "sl": 41,
    "replace_id": "18069",
    "replace_name": "Nazila Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "7-May-26",
    "new_sl": "41",
    "new_id": "18676",
    "new_name": "Jesmin Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "1-Aug-26",
    "remarks": ""
  },
  {
    "sl": 42,
    "replace_id": "18169",
    "replace_name": "Mehedi Hassan",
    "replace_designation": "Helper",
    "replace_section": "Fan Replace",
    "replace_doj": "9-Jun-26",
    "new_sl": "42",
    "new_id": "18675",
    "new_name": "Tahamid",
    "new_designation": "Helper",
    "new_section": "Fan Replacment",
    "new_doj": "1-Aug-26",
    "remarks": ""
  },
  {
    "sl": 43,
    "replace_id": "18016",
    "replace_name": "Khadija",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "30-Apr-26",
    "new_sl": "43",
    "new_id": "18674",
    "new_name": "Halima Begum",
    "new_designation": "Helper",
    "new_section": "Fan Dimmer and Blade",
    "new_doj": "1-Aug-26",
    "remarks": ""
  },
  {
    "sl": 44,
    "replace_id": "18656",
    "replace_name": "Semul Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "1-Aug-26",
    "new_sl": "44",
    "new_id": "18673",
    "new_name": "Afsana",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "1-Aug-26",
    "remarks": ""
  },
  {
    "sl": 45,
    "replace_id": "15368",
    "replace_name": "Mst. Liju Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "26-May-24",
    "new_sl": "45",
    "new_id": "18672",
    "new_name": "Rita  Rani",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "1-Aug-26",
    "remarks": ""
  },
  {
    "sl": 46,
    "replace_id": "18549",
    "replace_name": "Sanjida Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "19-Jul-26",
    "new_sl": "46",
    "new_id": "18659",
    "new_name": "Subarna Akter",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "1-Aug-26",
    "remarks": ""
  },
  {
    "sl": 47,
    "replace_id": "17417",
    "replace_name": "Orpa Bishas",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "0-Jan-00",
    "new_sl": "47",
    "new_id": "18658",
    "new_name": "Rupa Akter",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "1-Aug-26",
    "remarks": ""
  },
  {
    "sl": 48,
    "replace_id": "17987",
    "replace_name": "Sompa Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "26-Apr-26",
    "new_sl": "48",
    "new_id": "18657",
    "new_name": "Sanjida Akter",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "1-Aug-26",
    "remarks": ""
  },
  {
    "sl": 49,
    "replace_id": "14969",
    "replace_name": "Sumi Rani",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "9-Dec-23",
    "new_sl": "49",
    "new_id": "18656",
    "new_name": "Semul Akter",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "1-Aug-26",
    "remarks": ""
  },
  {
    "sl": 50,
    "replace_id": "17970",
    "replace_name": "Arifa",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "20-Apr-26",
    "new_sl": "50",
    "new_id": "18655",
    "new_name": "Tumpa Akter",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "1-Aug-26",
    "remarks": ""
  },
  {
    "sl": 51,
    "replace_id": "18433",
    "replace_name": "Sohan Howlader",
    "replace_designation": "Delivery Assistant",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "8-Jul-26",
    "new_sl": "51",
    "new_id": "18608",
    "new_name": "Robiul Islam",
    "new_designation": "Delivery Assistant",
    "new_section": "Fan Assemble Line",
    "new_doj": "1-Aug-26",
    "remarks": ""
  },
  {
    "sl": 52,
    "replace_id": "17623",
    "replace_name": "Farjana Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "9-Dec-25",
    "new_sl": "52",
    "new_id": "18609",
    "new_name": "Hriday Hawlader",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "26-Jul-26",
    "remarks": ""
  },
  {
    "sl": 53,
    "replace_id": "17347",
    "replace_name": "Misti Baroy",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "18-Oct-25",
    "new_sl": "53",
    "new_id": "18607",
    "new_name": "Sumi Begum",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "26-Jul-26",
    "remarks": ""
  },
  {
    "sl": 54,
    "replace_id": "868",
    "replace_name": "Abu Bokkor Siddik",
    "replace_designation": "Operator",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "13-Oct-16",
    "new_sl": "54",
    "new_id": "18595",
    "new_name": "Tisa Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "26-Jul-26",
    "remarks": ""
  },
  {
    "sl": 55,
    "replace_id": "17265",
    "replace_name": "Sukhi Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "11-Oct-25",
    "new_sl": "55",
    "new_id": "18594",
    "new_name": "Meherab Islam Jisan",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "26-Jul-26",
    "remarks": ""
  },
  {
    "sl": 56,
    "replace_id": "18016",
    "replace_name": "Khadija",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "30-Apr-26",
    "new_sl": "56",
    "new_id": "18577",
    "new_name": "Rayhana Ritu",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "26-Jul-26",
    "remarks": ""
  },
  {
    "sl": 57,
    "replace_id": "16207",
    "replace_name": "Md Rimon",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "9-Oct-24",
    "new_sl": "57",
    "new_id": "18576",
    "new_name": "Redwan Ullah",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "26-Jul-26",
    "remarks": ""
  },
  {
    "sl": 58,
    "replace_id": "18376",
    "replace_name": "Saddam Hossen Gazi",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "1-Jul-26",
    "new_sl": "58",
    "new_id": "18575",
    "new_name": "Hasan Mridha",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "26-Jul-26",
    "remarks": ""
  },
  {
    "sl": 59,
    "replace_id": "18160",
    "replace_name": "Urmy Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "8-Jun-26",
    "new_sl": "59",
    "new_id": "18574",
    "new_name": "Sathi Rani",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "21-Jul-26",
    "remarks": ""
  },
  {
    "sl": 60,
    "replace_id": "15854",
    "replace_name": "Ona Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "8-Sep-24",
    "new_sl": "60",
    "new_id": "18563",
    "new_name": "Mousumi Akter Sumi",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "20-Jul-26",
    "remarks": ""
  },
  {
    "sl": 61,
    "replace_id": "18214",
    "replace_name": "Rabeya Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "12-Jun-26",
    "new_sl": "61",
    "new_id": "18562",
    "new_name": "Rupali Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "20-Jul-26",
    "remarks": ""
  },
  {
    "sl": 62,
    "replace_id": "18326",
    "replace_name": "Parveen Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "26-Jun-26",
    "new_sl": "62",
    "new_id": "18549",
    "new_name": "Sanjida Akter",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "19-Jul-26",
    "remarks": ""
  },
  {
    "sl": 63,
    "replace_id": "18332",
    "replace_name": "Khadija",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "26-Jun-26",
    "new_sl": "63",
    "new_id": "18548",
    "new_name": "Bilkes Begum",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "19-Jul-26",
    "remarks": ""
  },
  {
    "sl": 64,
    "replace_id": "18332",
    "replace_name": "Khadija",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "26-Jun-26",
    "new_sl": "64",
    "new_id": "18511",
    "new_name": "Lamiya",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "15-Jul-26",
    "remarks": ""
  },
  {
    "sl": 65,
    "replace_id": "18306",
    "replace_name": "Md.Firoz Rahman Plabon",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "26-Jun-26",
    "new_sl": "65",
    "new_id": "18510",
    "new_name": "Sakil Rahaman",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "15-Jul-26",
    "remarks": ""
  },
  {
    "sl": 66,
    "replace_id": "17467",
    "replace_name": "Raihan Sikder",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "8-Nov-25",
    "new_sl": "66",
    "new_id": "18495",
    "new_name": "Mehedi Hassan",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "12-Jul-26",
    "remarks": ""
  },
  {
    "sl": 67,
    "replace_id": "1116",
    "replace_name": "Ity Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "21-Aug-16",
    "new_sl": "67",
    "new_id": "18494",
    "new_name": "Tanju Begum",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "12-Jul-26",
    "remarks": ""
  },
  {
    "sl": 68,
    "replace_id": "17916",
    "replace_name": "Arisha Islam Jarin",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "9-Apr-26",
    "new_sl": "68",
    "new_id": "18454",
    "new_name": "Hossain Howlader",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "9-Jul-26",
    "remarks": ""
  },
  {
    "sl": 69,
    "replace_id": "13786",
    "replace_name": "Monika Rani Datto",
    "replace_designation": "Helper",
    "replace_section": "Fan Rojonigondha",
    "replace_doj": "1-Feb-23",
    "new_sl": "69",
    "new_id": "18459",
    "new_name": "Kamrul Islam",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "8-Jul-26",
    "remarks": ""
  },
  {
    "sl": 70,
    "replace_id": "16596",
    "replace_name": "Mst. Helena Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Rojonigondha",
    "replace_doj": "4-Dec-24",
    "new_sl": "70",
    "new_id": "18435",
    "new_name": "Tamim Khan",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "8-Jul-26",
    "remarks": ""
  },
  {
    "sl": 71,
    "replace_id": "16022",
    "replace_name": "Israt Jahan Mitu",
    "replace_designation": "Helper",
    "replace_section": "Fan Rojonigondha",
    "replace_doj": "26-Sep-24",
    "new_sl": "71",
    "new_id": "18434",
    "new_name": "Rahaman akhon",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "8-Jul-26",
    "remarks": ""
  },
  {
    "sl": 72,
    "replace_id": "17828",
    "replace_name": "Prosanto Das",
    "replace_designation": "Delivery Asst.",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "8-Mar-26",
    "new_sl": "72",
    "new_id": "18433",
    "new_name": "Sohan Howlader",
    "new_designation": "Delivery Assistant",
    "new_section": "Fan Assemble Line",
    "new_doj": "8-Jul-26",
    "remarks": ""
  },
  {
    "sl": 73,
    "replace_id": "15689",
    "replace_name": "Urmi Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Rojonigondha",
    "replace_doj": "3-Aug-24",
    "new_sl": "73",
    "new_id": "18436",
    "new_name": "Mitu Akter",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "7-Jul-26",
    "remarks": ""
  },
  {
    "sl": 74,
    "replace_id": "17569",
    "replace_name": "Md.Nafiz Mahmud Rokon",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "29-Nov-25",
    "new_sl": "74",
    "new_id": "18390",
    "new_name": "Asraful Islam",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "2-Jul-26",
    "remarks": ""
  },
  {
    "sl": 75,
    "replace_id": "17887",
    "replace_name": "Sakaoet",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "7-Apr-26",
    "new_sl": "75",
    "new_id": "18376",
    "new_name": "Saddam Hossen Gazi",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "1-Jul-26",
    "remarks": ""
  },
  {
    "sl": 76,
    "replace_id": "2973",
    "replace_name": "Mst. Jasmin khanam",
    "replace_designation": "Operator",
    "replace_section": "Sada Shapla",
    "replace_doj": "3-Feb-16",
    "new_sl": "76",
    "new_id": "18375",
    "new_name": "Sumiya Akter",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "1-Jul-26",
    "remarks": ""
  },
  {
    "sl": 77,
    "replace_id": "16751",
    "replace_name": "Aysha Khatun",
    "replace_designation": "Helper",
    "replace_section": "Sada Shapla",
    "replace_doj": "26-Jan-25",
    "new_sl": "77",
    "new_id": "18367",
    "new_name": "Ayesha Begum",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "30-Jun-26",
    "remarks": ""
  },
  {
    "sl": 78,
    "replace_id": "18159",
    "replace_name": "Utpal Datta",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "13-Jun-26",
    "new_sl": "78",
    "new_id": "18315",
    "new_name": "Rabbi Howlader",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "27-Jun-26",
    "remarks": ""
  },
  {
    "sl": 79,
    "replace_id": "16083",
    "replace_name": "Sumiya Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "5-Oct-24",
    "new_sl": "79",
    "new_id": "18314",
    "new_name": "Sarmin Akter",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "27-Jun-26",
    "remarks": ""
  },
  {
    "sl": 80,
    "replace_id": "17573",
    "replace_name": "Mst. Jannatara Saraboni",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "29-Nov-25",
    "new_sl": "80",
    "new_id": "18313",
    "new_name": "Sathi Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "27-Jun-26",
    "remarks": ""
  },
  {
    "sl": 81,
    "replace_id": "17534",
    "replace_name": "Sorna Akter Sumi",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "19-Nov-25",
    "new_sl": "81",
    "new_id": "18312",
    "new_name": "Hafsa Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "27-Jun-26",
    "remarks": ""
  },
  {
    "sl": 82,
    "replace_id": "18160",
    "replace_name": "Urmy Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "8-Jun-26",
    "new_sl": "82",
    "new_id": "18311",
    "new_name": "Parveen Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "27-Jun-26",
    "remarks": ""
  },
  {
    "sl": 83,
    "replace_id": "17248",
    "replace_name": "Sabina Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "11-Oct-25",
    "new_sl": "83",
    "new_id": "18310",
    "new_name": "Md. Rasel",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "27-Jun-26",
    "remarks": ""
  },
  {
    "sl": 84,
    "replace_id": "18057",
    "replace_name": "Ovi Howlader",
    "replace_designation": "Helper",
    "replace_section": "Fan Rojonighondha",
    "replace_doj": "6-May-26",
    "new_sl": "84",
    "new_id": "18309",
    "new_name": "Risad Hawlader",
    "new_designation": "Helper",
    "new_section": "Fan Rojonigondha",
    "new_doj": "27-Jun-26",
    "remarks": ""
  },
  {
    "sl": 85,
    "replace_id": "18280",
    "replace_name": "Sarmin Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "20-Jun-26",
    "new_sl": "85",
    "new_id": "18332",
    "new_name": "Khadija",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "26-Jun-26",
    "remarks": ""
  },
  {
    "sl": 86,
    "replace_id": "18045",
    "replace_name": "Bayzid Hasan",
    "replace_designation": "Helper",
    "replace_section": "Fan Replacment",
    "replace_doj": "5-May-26",
    "new_sl": "86",
    "new_id": "18331",
    "new_name": "Ali Hassan",
    "new_designation": "Helper",
    "new_section": "Fan Replace",
    "new_doj": "26-Jun-26",
    "remarks": ""
  },
  {
    "sl": 87,
    "replace_id": "1116",
    "replace_name": "Ity Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "21-Aug-16",
    "new_sl": "87",
    "new_id": "18330",
    "new_name": "Sarmin Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "26-Jun-26",
    "remarks": ""
  },
  {
    "sl": 88,
    "replace_id": "14710",
    "replace_name": "Mala Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "8-Oct-23",
    "new_sl": "88",
    "new_id": "18329",
    "new_name": "Md.Rayhan",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "26-Jun-26",
    "remarks": ""
  },
  {
    "sl": 89,
    "replace_id": "18227",
    "replace_name": "Dip Chandra Shil",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "14-Jun-26",
    "new_sl": "89",
    "new_id": "18328",
    "new_name": "Arman",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "26-Jun-26",
    "remarks": ""
  },
  {
    "sl": 90,
    "replace_id": "18293",
    "replace_name": "Tarok Chandra Shea",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "21-Jun-26",
    "new_sl": "90",
    "new_id": "18327",
    "new_name": "Mostakin Hossen",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "26-Jun-26",
    "remarks": ""
  },
  {
    "sl": 91,
    "replace_id": "18162",
    "replace_name": "Anita Rani Saha",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "8-Jun-26",
    "new_sl": "91",
    "new_id": "18326",
    "new_name": "Parveen Akter",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "26-Jun-26",
    "remarks": ""
  },
  {
    "sl": 92,
    "replace_id": "17888",
    "replace_name": "Lipe",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "7-Apr-26",
    "new_sl": "92",
    "new_id": "18325",
    "new_name": "Sarmin Akter",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "26-Jun-26",
    "remarks": ""
  },
  {
    "sl": 93,
    "replace_id": "18263",
    "replace_name": "Mehedi Hassan",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "18-Jun-26",
    "new_sl": "93",
    "new_id": "18306",
    "new_name": "Md.Firoz Rahman Plabon",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "26-Jun-26",
    "remarks": ""
  },
  {
    "sl": 94,
    "replace_id": "17287",
    "replace_name": "Mst. Shathi Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "11-Oct-25",
    "new_sl": "94",
    "new_id": "18293",
    "new_name": "Tarok Chandra Shea",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "21-Jun-26",
    "remarks": ""
  },
  {
    "sl": 95,
    "replace_id": "18068",
    "replace_name": "Neazul Islam",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "7-May-26",
    "new_sl": "95",
    "new_id": "18292",
    "new_name": "Rakib Howlader",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "21-Jun-26",
    "remarks": ""
  },
  {
    "sl": 96,
    "replace_id": "18181",
    "replace_name": "Tanzila Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "10-Jun-26",
    "new_sl": "96",
    "new_id": "18291",
    "new_name": "Nure Jannat",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "21-Jun-26",
    "remarks": ""
  },
  {
    "sl": 97,
    "replace_id": "18279",
    "replace_name": "Tania Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Rojonigondha",
    "replace_doj": "20-Jun-26",
    "new_sl": "97",
    "new_id": "18290",
    "new_name": "Sima Akter",
    "new_designation": "Helper",
    "new_section": "Fan Rojonigondha",
    "new_doj": "21-Jun-26",
    "remarks": ""
  },
  {
    "sl": 98,
    "replace_id": "11634",
    "replace_name": "Akhi Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Rojonigondha",
    "replace_doj": "7-Mar-21",
    "new_sl": "98",
    "new_id": "18281",
    "new_name": "Sathi Akter",
    "new_designation": "Helper",
    "new_section": "Fan Rojonigondha",
    "new_doj": "20-Jun-26",
    "remarks": ""
  },
  {
    "sl": 99,
    "replace_id": "17890",
    "replace_name": "Tania Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "7-Apr-26",
    "new_sl": "99",
    "new_id": "18280",
    "new_name": "Sarmin Begum",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "20-Jun-26",
    "remarks": ""
  },
  {
    "sl": 100,
    "replace_id": "2904",
    "replace_name": "Shahida Akter Lipi",
    "replace_designation": "Helper",
    "replace_section": "Sada Shapla",
    "replace_doj": "10-Feb-15",
    "new_sl": "100",
    "new_id": "18278",
    "new_name": "Nilufa",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "20-Jun-26",
    "remarks": ""
  },
  {
    "sl": 101,
    "replace_id": "18179",
    "replace_name": "Asikur Rahaman",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "10-Jun-26",
    "new_sl": "101",
    "new_id": "18263",
    "new_name": "Mehedi Hassan",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "18-Jun-26",
    "remarks": ""
  },
  {
    "sl": 102,
    "replace_id": "17259",
    "replace_name": "Mst. Kaya Akter Tania",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "11-Oct-25",
    "new_sl": "102",
    "new_id": "18255",
    "new_name": "Jahid hasan Rakib",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "17-Jun-26",
    "remarks": ""
  },
  {
    "sl": 103,
    "replace_id": "10570",
    "replace_name": "Mim Akter",
    "replace_designation": "Asst. Operator",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "7-Sep-20",
    "new_sl": "103",
    "new_id": "18253",
    "new_name": "Mim Akter Suma",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "17-Jun-26",
    "remarks": ""
  },
  {
    "sl": 104,
    "replace_id": "17379",
    "replace_name": "Md. Asif Howlader",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "19-Oct-25",
    "new_sl": "104",
    "new_id": "18230",
    "new_name": "Rabiul Khandoker",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "14-Jun-26",
    "remarks": ""
  },
  {
    "sl": 105,
    "replace_id": "14926",
    "replace_name": "Alo Rani",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "26-Nov-23",
    "new_sl": "105",
    "new_id": "18228",
    "new_name": "Suparna Roy",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "14-Jun-26",
    "remarks": ""
  },
  {
    "sl": 106,
    "replace_id": "17619",
    "replace_name": "Fathema Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "9-Dec-25",
    "new_sl": "106",
    "new_id": "18227",
    "new_name": "Dip Chandra Shil",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "14-Jun-26",
    "remarks": ""
  },
  {
    "sl": 107,
    "replace_id": "17275",
    "replace_name": "Md. Robiul Bishas",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "11-Oct-25",
    "new_sl": "107",
    "new_id": "18206",
    "new_name": "Apu Sikder",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "13-Jun-26",
    "remarks": ""
  },
  {
    "sl": 108,
    "replace_id": "17519",
    "replace_name": "Mst. Sathi Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "15-Nov-25",
    "new_sl": "108",
    "new_id": "18205",
    "new_name": "Shilpe  Rani Shil",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "13-Jun-26",
    "remarks": ""
  },
  {
    "sl": 109,
    "replace_id": "17246",
    "replace_name": "Sima Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "11-Oct-25",
    "new_sl": "109",
    "new_id": "18204",
    "new_name": "Putul Rani Das",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "13-Jun-26",
    "remarks": ""
  },
  {
    "sl": 110,
    "replace_id": "18127",
    "replace_name": "Seuli Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "6-Jun-26",
    "new_sl": "110",
    "new_id": "18203",
    "new_name": "Dalia Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "13-Jun-26",
    "remarks": ""
  },
  {
    "sl": 111,
    "replace_id": "17948",
    "replace_name": "Newton",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "17-Apr-26",
    "new_sl": "111",
    "new_id": "18159",
    "new_name": "Utpal Datta",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "13-Jun-26",
    "remarks": ""
  },
  {
    "sl": 112,
    "replace_id": "17558",
    "replace_name": "Md. Kalam Howlader",
    "replace_designation": "Operator",
    "replace_section": "Fan Lathe",
    "replace_doj": "3-Dec-25",
    "new_sl": "112",
    "new_id": "18126",
    "new_name": "MD.Sakil",
    "new_designation": "Operator",
    "new_section": "Fan Lathe",
    "new_doj": "13-Jun-26",
    "remarks": ""
  },
  {
    "sl": 113,
    "replace_id": "18161",
    "replace_name": "Tulsi Rani",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "8-Jun-26",
    "new_sl": "113",
    "new_id": "18214",
    "new_name": "Rabeya Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "12-Jun-26",
    "remarks": ""
  },
  {
    "sl": 114,
    "replace_id": "17383",
    "replace_name": "Fatema Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "0-Jan-00",
    "new_sl": "114",
    "new_id": "18213",
    "new_name": "Fatema Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "12-Jun-26",
    "remarks": ""
  },
  {
    "sl": 115,
    "replace_id": "16355",
    "replace_name": "Nodi Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "28-Oct-24",
    "new_sl": "115",
    "new_id": "18212",
    "new_name": "Fatema Akter Mitu",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "12-Jun-26",
    "remarks": ""
  },
  {
    "sl": 116,
    "replace_id": "17581",
    "replace_name": "Moyba Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "2-Dec-25",
    "new_sl": "116",
    "new_id": "18182",
    "new_name": "Dipa Rani saha",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "10-Jun-26",
    "remarks": ""
  },
  {
    "sl": 117,
    "replace_id": "17967",
    "replace_name": "Tania Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "20-Apr-26",
    "new_sl": "117",
    "new_id": "18181",
    "new_name": "Tanzila Akter",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "10-Jun-26",
    "remarks": ""
  },
  {
    "sl": 118,
    "replace_id": "15505",
    "replace_name": "Maya Rani",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "6-Jul-24",
    "new_sl": "118",
    "new_id": "18180",
    "new_name": "Mim Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "10-Jun-26",
    "remarks": ""
  },
  {
    "sl": 119,
    "replace_id": "17468",
    "replace_name": "Araf Hossen",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "0-Jan-00",
    "new_sl": "119",
    "new_id": "18179",
    "new_name": "Asikur Rahaman",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "10-Jun-26",
    "remarks": ""
  },
  {
    "sl": 120,
    "replace_id": "17852",
    "replace_name": "Maharaj",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "2-Apr-26",
    "new_sl": "120",
    "new_id": "18178",
    "new_name": "Rezaul",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "10-Jun-26",
    "remarks": ""
  },
  {
    "sl": 121,
    "replace_id": "18029",
    "replace_name": "Mirajul Islam",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "4-May-26",
    "new_sl": "121",
    "new_id": "18177",
    "new_name": "Sajol Hossain",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "10-Jun-26",
    "remarks": ""
  },
  {
    "sl": 122,
    "replace_id": "17657",
    "replace_name": "Anisur Rahaman",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "15-Dec-25",
    "new_sl": "122",
    "new_id": "18170",
    "new_name": "Zihad Gazi",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "9-Jun-26",
    "remarks": ""
  },
  {
    "sl": 123,
    "replace_id": "18062",
    "replace_name": "Tahmid Uddin",
    "replace_designation": "Helper",
    "replace_section": "Fan Replacment",
    "replace_doj": "6-May-26",
    "new_sl": "123",
    "new_id": "18169",
    "new_name": "Mehedi Hassan",
    "new_designation": "Helper",
    "new_section": "Fan Replace",
    "new_doj": "9-Jun-26",
    "remarks": ""
  },
  {
    "sl": 124,
    "replace_id": "14876",
    "replace_name": "Nazmin Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Rojonigondha",
    "replace_doj": "11-Nov-23",
    "new_sl": "124",
    "new_id": "18162",
    "new_name": "Anita Rani Saha",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "8-Jun-26",
    "remarks": ""
  },
  {
    "sl": 125,
    "replace_id": "17422",
    "replace_name": "Mim Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "0-Jan-00",
    "new_sl": "125",
    "new_id": "18161",
    "new_name": "Tulsi Rani",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "8-Jun-26",
    "remarks": ""
  },
  {
    "sl": 126,
    "replace_id": "17374",
    "replace_name": "Mst. Mim",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "18-Oct-25",
    "new_sl": "126",
    "new_id": "18160",
    "new_name": "Urmy Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "8-Jun-26",
    "remarks": ""
  },
  {
    "sl": 127,
    "replace_id": "18046",
    "replace_name": "Jannatul Ferdous",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "5-May-26",
    "new_sl": "127",
    "new_id": "18140",
    "new_name": "Mim Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "7-Jun-26",
    "remarks": ""
  },
  {
    "sl": 128,
    "replace_id": "16754",
    "replace_name": "Kakoli",
    "replace_designation": "Helper",
    "replace_section": "Fan Rojonigondha",
    "replace_doj": "26-Jan-25",
    "new_sl": "128",
    "new_id": "18130",
    "new_name": "Repanur Asha",
    "new_designation": "Helper",
    "new_section": "Fan Rojonighondha",
    "new_doj": "7-Jun-26",
    "remarks": ""
  },
  {
    "sl": 129,
    "replace_id": "823",
    "replace_name": "Parvin Begum",
    "replace_designation": "Asst. Operator",
    "replace_section": "Fan Lathe",
    "replace_doj": "13-Nov-16",
    "new_sl": "129",
    "new_id": "18129",
    "new_name": "Anjona Rani",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "6-Jun-26",
    "remarks": ""
  },
  {
    "sl": 130,
    "replace_id": "18047",
    "replace_name": "Doli",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "5-May-26",
    "new_sl": "130",
    "new_id": "18128",
    "new_name": "Shilpe Akter",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "6-Jun-26",
    "remarks": ""
  },
  {
    "sl": 131,
    "replace_id": "18096",
    "replace_name": "Ruma Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "13-May-26",
    "new_sl": "131",
    "new_id": "18127",
    "new_name": "Seuli Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "6-Jun-26",
    "remarks": ""
  },
  {
    "sl": 132,
    "replace_id": "1429",
    "replace_name": "Subrata Chandra Halder",
    "replace_designation": "Asst. Operator",
    "replace_section": "Fan Lathe",
    "replace_doj": "20-Feb-18",
    "new_sl": "132",
    "new_id": "18119",
    "new_name": "Harun or Rasid",
    "new_designation": "Operator",
    "new_section": "Fan Lathe",
    "new_doj": "3-Jun-26",
    "remarks": ""
  },
  {
    "sl": 133,
    "replace_id": "17854",
    "replace_name": "Sholyman",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "5-Apr-26",
    "new_sl": "133",
    "new_id": "18108",
    "new_name": "Rayhan Hasan",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "17-May-26",
    "remarks": ""
  },
  {
    "sl": 134,
    "replace_id": "18060",
    "replace_name": "Jannat Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "6-May-26",
    "new_sl": "134",
    "new_id": "18096",
    "new_name": "Ruma Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "13-May-26",
    "remarks": ""
  },
  {
    "sl": 135,
    "replace_id": "17421",
    "replace_name": "Lamia Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "0-Jan-00",
    "new_sl": "135",
    "new_id": "18095",
    "new_name": "Eti Halder",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "13-May-26",
    "remarks": ""
  },
  {
    "sl": 136,
    "replace_id": "18047",
    "replace_name": "Doli",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "5-May-26",
    "new_sl": "136",
    "new_id": "18094",
    "new_name": "MD.Ferdous",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "13-May-26",
    "remarks": ""
  },
  {
    "sl": 137,
    "replace_id": "17349",
    "replace_name": "Ritu Biswas",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "18-Oct-25",
    "new_sl": "137",
    "new_id": "18070",
    "new_name": "Siyam Molla",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "7-May-26",
    "remarks": ""
  },
  {
    "sl": 138,
    "replace_id": "17915",
    "replace_name": "Rabbi Howlader",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "9-Apr-26",
    "new_sl": "138",
    "new_id": "18069",
    "new_name": "Nazila Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "7-May-26",
    "remarks": ""
  },
  {
    "sl": 139,
    "replace_id": "17968",
    "replace_name": "Mahafuja",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "20-Apr-26",
    "new_sl": "139",
    "new_id": "18068",
    "new_name": "Neazul Islam",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "7-May-26",
    "remarks": ""
  },
  {
    "sl": 140,
    "replace_id": "17949",
    "replace_name": "Akash",
    "replace_designation": "Helper",
    "replace_section": "Fan Replace",
    "replace_doj": "17-Apr-26",
    "new_sl": "140",
    "new_id": "18062",
    "new_name": "Tahmid Uddin",
    "new_designation": "Helper",
    "new_section": "Fan Replacment",
    "new_doj": "6-May-26",
    "remarks": ""
  },
  {
    "sl": 141,
    "replace_id": "17727",
    "replace_name": "Oli Ahmad",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "13-Jan-26",
    "new_sl": "141",
    "new_id": "18061",
    "new_name": "Beauty Begum",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "6-May-26",
    "remarks": ""
  },
  {
    "sl": 142,
    "replace_id": "18017",
    "replace_name": "Sumi Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "30-Apr-26",
    "new_sl": "142",
    "new_id": "18060",
    "new_name": "Jannat Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "6-May-26",
    "remarks": ""
  },
  {
    "sl": 143,
    "replace_id": "17292",
    "replace_name": "Moriom",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "11-Oct-25",
    "new_sl": "143",
    "new_id": "18059",
    "new_name": "Chadni Akter",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "6-May-26",
    "remarks": ""
  },
  {
    "sl": 144,
    "replace_id": "17852",
    "replace_name": "Maharaj",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "2-Apr-26",
    "new_sl": "144",
    "new_id": "18058",
    "new_name": "Ms Purnima Akther",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "6-May-26",
    "remarks": ""
  },
  {
    "sl": 145,
    "replace_id": "12414",
    "replace_name": "Sonjida Rani Deury",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "13-Oct-21",
    "new_sl": "145",
    "new_id": "18056",
    "new_name": "Laizu Begum",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "6-May-26",
    "remarks": ""
  },
  {
    "sl": 146,
    "replace_id": "17934",
    "replace_name": "Tamanna",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "12-Apr-26",
    "new_sl": "146",
    "new_id": "18047",
    "new_name": "Doli",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "5-May-26",
    "remarks": ""
  },
  {
    "sl": 147,
    "replace_id": "17257",
    "replace_name": "Mst. Fatema Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "18-Oct-25",
    "new_sl": "147",
    "new_id": "18046",
    "new_name": "Jannatul Ferdous",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "5-May-26",
    "remarks": ""
  },
  {
    "sl": 148,
    "replace_id": "17950",
    "replace_name": "yeasin",
    "replace_designation": "Helper",
    "replace_section": "Fan Replace",
    "replace_doj": "17-Apr-26",
    "new_sl": "148",
    "new_id": "18045",
    "new_name": "Bayzid Hasan",
    "new_designation": "Helper",
    "new_section": "Fan Replacment",
    "new_doj": "5-May-26",
    "remarks": ""
  },
  {
    "sl": 149,
    "replace_id": "17997",
    "replace_name": "Sakir Ahamed",
    "replace_designation": "Helper",
    "replace_section": "Fan Rojonighondha",
    "replace_doj": "27-Apr-26",
    "new_sl": "149",
    "new_id": "18030",
    "new_name": "Porosh",
    "new_designation": "Helper",
    "new_section": "Fan Rojonigondha",
    "new_doj": "4-May-26",
    "remarks": ""
  },
  {
    "sl": 150,
    "replace_id": "17608",
    "replace_name": "Md Enamul Shikder",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "4-Dec-25",
    "new_sl": "150",
    "new_id": "18029",
    "new_name": "Mirajul Islam",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "4-May-26",
    "remarks": ""
  },
  {
    "sl": 151,
    "replace_id": "16100",
    "replace_name": "Bristy Khatun",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "6-Oct-24",
    "new_sl": "151",
    "new_id": "18017",
    "new_name": "Sumi Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "30-Apr-26",
    "remarks": ""
  },
  {
    "sl": 152,
    "replace_id": "17966",
    "replace_name": "Mukta Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "20-Apr-26",
    "new_sl": "152",
    "new_id": "18016",
    "new_name": "Khadija",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "30-Apr-26",
    "remarks": ""
  },
  {
    "sl": 153,
    "replace_id": "17679",
    "replace_name": "Kobita",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "27-Dec-25",
    "new_sl": "153",
    "new_id": "17998",
    "new_name": "Molina Biswas",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "27-Apr-26",
    "remarks": ""
  },
  {
    "sl": 154,
    "replace_id": "15403",
    "replace_name": "Rezaz Ahamad",
    "replace_designation": "Helper",
    "replace_section": "Sada Shapla",
    "replace_doj": "5-Jun-24",
    "new_sl": "154",
    "new_id": "17997",
    "new_name": "Sakir Ahamed",
    "new_designation": "Helper",
    "new_section": "Fan Rojonighondha",
    "new_doj": "27-Apr-26",
    "remarks": ""
  },
  {
    "sl": 155,
    "replace_id": "14595",
    "replace_name": "Tania Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Auto Powder Coating",
    "replace_doj": "13-Sep-23",
    "new_sl": "155",
    "new_id": "17987",
    "new_name": "Sompa Akter",
    "new_designation": "Helper",
    "new_section": "Fan Auto Powder Coating",
    "new_doj": "26-Apr-26",
    "remarks": ""
  },
  {
    "sl": 156,
    "replace_id": "17932",
    "replace_name": "Sukhi Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "12-Apr-26",
    "new_sl": "156",
    "new_id": "17971",
    "new_name": "Lamiya",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "20-Apr-26",
    "remarks": ""
  },
  {
    "sl": 157,
    "replace_id": "17280",
    "replace_name": "Md. Shakil Howlader",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "11-Oct-25",
    "new_sl": "157",
    "new_id": "17970",
    "new_name": "Arifa",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "20-Apr-26",
    "remarks": ""
  },
  {
    "sl": 158,
    "replace_id": "17891",
    "replace_name": "Eity Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "7-Apr-26",
    "new_sl": "158",
    "new_id": "17968",
    "new_name": "Mahafuja",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "20-Apr-26",
    "remarks": ""
  },
  {
    "sl": 159,
    "replace_id": "17929",
    "replace_name": "Pori Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "12-Apr-26",
    "new_sl": "159",
    "new_id": "17967",
    "new_name": "Tania Akter",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "20-Apr-26",
    "remarks": ""
  },
  {
    "sl": 160,
    "replace_id": "17576",
    "replace_name": "Dipa Rani Saha",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "1-Dec-25",
    "new_sl": "160",
    "new_id": "17966",
    "new_name": "Mukta Akter",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "20-Apr-26",
    "remarks": ""
  },
  {
    "sl": 161,
    "replace_id": "17261",
    "replace_name": "Md. Hasad",
    "replace_designation": "Helper",
    "replace_section": "Fan Replace",
    "replace_doj": "11-Oct-25",
    "new_sl": "161",
    "new_id": "17950",
    "new_name": "yeasin",
    "new_designation": "Helper",
    "new_section": "Fan Replace",
    "new_doj": "17-Apr-26",
    "remarks": ""
  },
  {
    "sl": 162,
    "replace_id": "15625",
    "replace_name": "Sayem Islam Rahat",
    "replace_designation": "Helper",
    "replace_section": "Fan Replace",
    "replace_doj": "18-Jul-24",
    "new_sl": "162",
    "new_id": "17949",
    "new_name": "Akash",
    "new_designation": "Helper",
    "new_section": "Fan Replace",
    "new_doj": "17-Apr-26",
    "remarks": ""
  },
  {
    "sl": 163,
    "replace_id": "17626",
    "replace_name": "Sakibul Islam",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "9-Dec-25",
    "new_sl": "163",
    "new_id": "17934",
    "new_name": "Tamanna",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "12-Apr-26",
    "remarks": ""
  },
  {
    "sl": 164,
    "replace_id": "17858",
    "replace_name": "Sathi Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "4-Apr-26",
    "new_sl": "164",
    "new_id": "17932",
    "new_name": "Sukhi Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "12-Apr-26",
    "remarks": ""
  },
  {
    "sl": 165,
    "replace_id": "17350",
    "replace_name": "Sumaiya Akter Mow",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "18-Oct-25",
    "new_sl": "165",
    "new_id": "17930",
    "new_name": "Urmy Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "12-Apr-26",
    "remarks": ""
  },
  {
    "sl": 166,
    "replace_id": "17860",
    "replace_name": "Amina khatun",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "4-Apr-26",
    "new_sl": "166",
    "new_id": "17929",
    "new_name": "Pori Akter",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "12-Apr-26",
    "remarks": ""
  },
  {
    "sl": 167,
    "replace_id": "15352",
    "replace_name": "Jannat",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "20-May-24",
    "new_sl": "167",
    "new_id": "17918",
    "new_name": "Sumaya Akter",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "9-Apr-26",
    "remarks": ""
  },
  {
    "sl": 168,
    "replace_id": "17293",
    "replace_name": "Urmi Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "11-Oct-25",
    "new_sl": "168",
    "new_id": "17917",
    "new_name": "Jannatul Islam",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "9-Apr-26",
    "remarks": ""
  },
  {
    "sl": 169,
    "replace_id": "17245",
    "replace_name": "Lakhi Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "11-Oct-25",
    "new_sl": "169",
    "new_id": "17916",
    "new_name": "Arisha Islam Jarin",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "9-Apr-26",
    "remarks": ""
  },
  {
    "sl": 170,
    "replace_id": "17862",
    "replace_name": "Jahaid",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "4-Apr-26",
    "new_sl": "170",
    "new_id": "17915",
    "new_name": "Rabbi Howlader",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "9-Apr-26",
    "remarks": ""
  },
  {
    "sl": 171,
    "replace_id": "17483",
    "replace_name": "Hira Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "10-Nov-25",
    "new_sl": "171",
    "new_id": "17914",
    "new_name": "Laki Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "9-Apr-26",
    "remarks": ""
  },
  {
    "sl": 172,
    "replace_id": "17847",
    "replace_name": "Sonia Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "1-Apr-26",
    "new_sl": "172",
    "new_id": "17890",
    "new_name": "Tania Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "7-Apr-26",
    "remarks": ""
  },
  {
    "sl": 173,
    "replace_id": "17861",
    "replace_name": "Hena Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "4-Apr-26",
    "new_sl": "173",
    "new_id": "17889",
    "new_name": "Habiba",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "7-Apr-26",
    "remarks": ""
  },
  {
    "sl": 174,
    "replace_id": "17310",
    "replace_name": "Nazmin Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "11-Oct-25",
    "new_sl": "174",
    "new_id": "17888",
    "new_name": "Lipe",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "7-Apr-26",
    "remarks": ""
  },
  {
    "sl": 175,
    "replace_id": "17355",
    "replace_name": "Bijan Kumar Das",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "18-Oct-25",
    "new_sl": "175",
    "new_id": "17887",
    "new_name": "Sakaoet",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "7-Apr-26",
    "remarks": ""
  },
  {
    "sl": 176,
    "replace_id": "17324",
    "replace_name": "Md. Foysal Howlader",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "13-Oct-25",
    "new_sl": "176",
    "new_id": "17886",
    "new_name": "Mamun Howlader",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "7-Apr-26",
    "remarks": ""
  },
  {
    "sl": 177,
    "replace_id": "16467",
    "replace_name": "Md Parves Sarder",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "5-Nov-24",
    "new_sl": "177",
    "new_id": "17854",
    "new_name": "Sholyman",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "5-Apr-26",
    "remarks": ""
  },
  {
    "sl": 178,
    "replace_id": "17598",
    "replace_name": "MD. Halim Khan",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "3-Dec-25",
    "new_sl": "178",
    "new_id": "17862",
    "new_name": "Jahaid",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "4-Apr-26",
    "remarks": ""
  },
  {
    "sl": 179,
    "replace_id": "17618",
    "replace_name": "Samima Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "9-Dec-25",
    "new_sl": "179",
    "new_id": "17861",
    "new_name": "Hena Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "4-Apr-26",
    "remarks": ""
  },
  {
    "sl": 180,
    "replace_id": "17567",
    "replace_name": "Mim Aktert",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "29-Nov-25",
    "new_sl": "180",
    "new_id": "17860",
    "new_name": "Amina khatun",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "4-Apr-26",
    "remarks": ""
  },
  {
    "sl": 181,
    "replace_id": "15075",
    "replace_name": "Sukhi Akter",
    "replace_designation": "Helper",
    "replace_section": "Sada Shapla",
    "replace_doj": "13-Jan-24",
    "new_sl": "181",
    "new_id": "17859",
    "new_name": "Tanjila akter",
    "new_designation": "Helper",
    "new_section": "Fan Rojonigondha",
    "new_doj": "4-Apr-26",
    "remarks": ""
  },
  {
    "sl": 182,
    "replace_id": "17582",
    "replace_name": "Mst. Kulsum Bibi Jui",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "2-Dec-25",
    "new_sl": "182",
    "new_id": "17858",
    "new_name": "Sathi Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "4-Apr-26",
    "remarks": ""
  },
  {
    "sl": 183,
    "replace_id": "17599",
    "replace_name": "Khukumoni Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "3-Dec-25",
    "new_sl": "183",
    "new_id": "17857",
    "new_name": "Elma Akter mou",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "4-Apr-26",
    "remarks": ""
  },
  {
    "sl": 184,
    "replace_id": "17678",
    "replace_name": "Jannatul Ferdous",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "27-Dec-25",
    "new_sl": "184",
    "new_id": "17856",
    "new_name": "Eti khatun",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "4-Apr-26",
    "remarks": ""
  },
  {
    "sl": 185,
    "replace_id": "17560",
    "replace_name": "Md. Munna Howlader",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "26-Nov-25",
    "new_sl": "185",
    "new_id": "17853",
    "new_name": "Mehedi",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "2-Apr-26",
    "remarks": ""
  },
  {
    "sl": 186,
    "replace_id": "17565",
    "replace_name": "Md Siddik Mridha",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "29-Nov-25",
    "new_sl": "186",
    "new_id": "17852",
    "new_name": "Maharaj",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "2-Apr-26",
    "remarks": ""
  },
  {
    "sl": 187,
    "replace_id": "17568",
    "replace_name": "Munni Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "29-Nov-25",
    "new_sl": "187",
    "new_id": "17848",
    "new_name": "Bithi Akter",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "1-Apr-26",
    "remarks": ""
  },
  {
    "sl": 188,
    "replace_id": "17250",
    "replace_name": "Sanjida",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "18-Oct-25",
    "new_sl": "188",
    "new_id": "17847",
    "new_name": "Sonia Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "1-Apr-26",
    "remarks": ""
  },
  {
    "sl": 189,
    "replace_id": "17532",
    "replace_name": "Md. Mehedi Hasan Tanzil",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "18-Nov-25",
    "new_sl": "189",
    "new_id": "17731",
    "new_name": "Afaz Fahmud",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "14-Jan-26",
    "remarks": ""
  },
  {
    "sl": 190,
    "replace_id": "17560",
    "replace_name": "Md. Munna Howlader",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "26-Nov-25",
    "new_sl": "190",
    "new_id": "17727",
    "new_name": "Oli Ahmad",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "13-Jan-26",
    "remarks": ""
  },
  {
    "sl": 191,
    "replace_id": "16473",
    "replace_name": "Bristy",
    "replace_designation": "Asst. Operator",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "6-Nov-24",
    "new_sl": "191",
    "new_id": "17725",
    "new_name": "Md.Nayem Hossain",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "12-Jan-26",
    "remarks": ""
  },
  {
    "sl": 192,
    "replace_id": "17625",
    "replace_name": "Mst.Lima Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "9-Dec-25",
    "new_sl": "192",
    "new_id": "17679",
    "new_name": "Kobita",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "27-Dec-25",
    "remarks": ""
  },
  {
    "sl": 193,
    "replace_id": "17320",
    "replace_name": "Sumi Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "18-Oct-25",
    "new_sl": "193",
    "new_id": "17678",
    "new_name": "Jannatul Ferdous",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "27-Dec-25",
    "remarks": ""
  },
  {
    "sl": 194,
    "replace_id": "17252",
    "replace_name": "Mst. Sharmin Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "11-Oct-25",
    "new_sl": "194",
    "new_id": "17626",
    "new_name": "Sakibul Islam",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "9-Dec-25",
    "remarks": ""
  },
  {
    "sl": 195,
    "replace_id": "17419",
    "replace_name": "Rimon Shek",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "0-Jan-00",
    "new_sl": "195",
    "new_id": "17625",
    "new_name": "Mst.Lima Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "9-Dec-25",
    "remarks": ""
  },
  {
    "sl": 196,
    "replace_id": "17570",
    "replace_name": "Muna Akter Mim",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "29-Nov-25",
    "new_sl": "196",
    "new_id": "17624",
    "new_name": "Afsana Mimi",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "9-Dec-25",
    "remarks": ""
  },
  {
    "sl": 197,
    "replace_id": "17260",
    "replace_name": "Md. Main Uddin Hossen Hridoy",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "11-Oct-25",
    "new_sl": "197",
    "new_id": "17623",
    "new_name": "Farjana Akter",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "9-Dec-25",
    "remarks": ""
  },
  {
    "sl": 198,
    "replace_id": "17518",
    "replace_name": "Kartik Das",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "15-Nov-25",
    "new_sl": "198",
    "new_id": "17622",
    "new_name": "Mst. Mukta Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "9-Dec-25",
    "remarks": ""
  },
  {
    "sl": 199,
    "replace_id": "17244",
    "replace_name": "Fatema",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "11-Oct-25",
    "new_sl": "199",
    "new_id": "17621",
    "new_name": "Khukumoni",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "9-Dec-25",
    "remarks": ""
  },
  {
    "sl": 200,
    "replace_id": "17382",
    "replace_name": "Israt Jahan Poly",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "0-Jan-00",
    "new_sl": "200",
    "new_id": "17620",
    "new_name": "Shakibul  Islam,",
    "new_designation": "Delivery Asst.",
    "new_section": "Fan Assemble Line",
    "new_doj": "9-Dec-25",
    "remarks": ""
  },
  {
    "sl": 201,
    "replace_id": "17262",
    "replace_name": "Md. Ali Hasan",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "11-Oct-25",
    "new_sl": "201",
    "new_id": "17619",
    "new_name": "Fathema Begum",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "9-Dec-25",
    "remarks": ""
  },
  {
    "sl": 202,
    "replace_id": "17469",
    "replace_name": "Sumiya Akter Mim",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "0-Jan-00",
    "new_sl": "202",
    "new_id": "17618",
    "new_name": "Samima Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "9-Dec-25",
    "remarks": ""
  },
  {
    "sl": 203,
    "replace_id": "17377",
    "replace_name": "Mst. Jannat Islam",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "18-Oct-25",
    "new_sl": "203",
    "new_id": "17599",
    "new_name": "Khukumoni Akter",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "3-Dec-25",
    "remarks": ""
  },
  {
    "sl": 204,
    "replace_id": "17379",
    "replace_name": "Md. Asif Howlader",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "19-Oct-25",
    "new_sl": "204",
    "new_id": "17597",
    "new_name": "Md Rakib Gazi",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "3-Dec-25",
    "remarks": ""
  },
  {
    "sl": 205,
    "replace_id": "17487",
    "replace_name": "Aysha",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "10-Nov-25",
    "new_sl": "205",
    "new_id": "17576",
    "new_name": "Dipa Rani Saha",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "1-Dec-25",
    "remarks": ""
  },
  {
    "sl": 206,
    "replace_id": "17286",
    "replace_name": "Rujina Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "18-Oct-25",
    "new_sl": "206",
    "new_id": "17573",
    "new_name": "Mst. Jannatara Saraboni",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "29-Nov-25",
    "remarks": ""
  },
  {
    "sl": 207,
    "replace_id": "17416",
    "replace_name": "Sumi Akter (2)",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "0-Jan-00",
    "new_sl": "207",
    "new_id": "17570",
    "new_name": "Muna Akter Mim",
    "new_designation": "Helper",
    "new_section": "Fan Assemble Line",
    "new_doj": "29-Nov-25",
    "remarks": ""
  },
  {
    "sl": 208,
    "replace_id": "17271",
    "replace_name": "Sayedur Rahman",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "11-Oct-25",
    "new_sl": "208",
    "new_id": "17569",
    "new_name": "Md.Nafiz Mahmud Rokon",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "29-Nov-25",
    "remarks": ""
  },
  {
    "sl": 209,
    "replace_id": "17282",
    "replace_name": "Fatema Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "18-Oct-25",
    "new_sl": "209",
    "new_id": "17568",
    "new_name": "Munni Akter",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "29-Nov-25",
    "remarks": ""
  },
  {
    "sl": 210,
    "replace_id": "17255",
    "replace_name": "Santa Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "18-Oct-25",
    "new_sl": "210",
    "new_id": "17567",
    "new_name": "Mim Aktert",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "29-Nov-25",
    "remarks": ""
  },
  {
    "sl": 211,
    "replace_id": "17264",
    "replace_name": "Maria Akter Jui",
    "replace_designation": "Helper",
    "replace_section": "Fan Assemble Line",
    "replace_doj": "18-Oct-25",
    "new_sl": "211",
    "new_id": "17566",
    "new_name": "Urmi Akter Mim",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "29-Nov-25",
    "remarks": ""
  },
  {
    "sl": 212,
    "replace_id": "17272",
    "replace_name": "Abid Hossain Santo",
    "replace_designation": "Helper",
    "replace_section": "Fan Power Press & Stamping",
    "replace_doj": "11-Oct-25",
    "new_sl": "212",
    "new_id": "17565",
    "new_name": "Md Siddik Mridha",
    "new_designation": "Helper",
    "new_section": "Fan Power Press & Stamping",
    "new_doj": "29-Nov-25",
    "remarks": ""
  },
  {
    "sl": 213,
    "replace_id": "17445",
    "replace_name": "Romjan",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "4-Nov-25",
    "new_sl": "213",
    "new_id": "17535",
    "new_name": "Md. Rafikul Khan",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "19-Nov-25",
    "remarks": ""
  },
  {
    "sl": 214,
    "replace_id": "17480",
    "replace_name": "Munni Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "10-Nov-25",
    "new_sl": "214",
    "new_id": "17534",
    "new_name": "Sorna Akter Sumi",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "19-Nov-25",
    "remarks": ""
  },
  {
    "sl": 215,
    "replace_id": "17309",
    "replace_name": "Shri Krisna Sazzal",
    "replace_designation": "Helper",
    "replace_section": "Fan Dhalai & Die Casting",
    "replace_doj": "11-Oct-25",
    "new_sl": "215",
    "new_id": "17532",
    "new_name": "Md. Mehedi Hasan Tanzil",
    "new_designation": "Helper",
    "new_section": "Fan Dhalai & Die Casting",
    "new_doj": "18-Nov-25",
    "remarks": ""
  },
  {
    "sl": 216,
    "replace_id": "17524",
    "replace_name": "Liton Chandra Howlader",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "16-Nov-25",
    "new_sl": "216",
    "new_id": "17531",
    "new_name": "Md. Siraj Uddin Talukder",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "18-Nov-25",
    "remarks": ""
  },
  {
    "sl": 217,
    "replace_id": "17490",
    "replace_name": "Rakib Howlader",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "10-Nov-25",
    "new_sl": "217",
    "new_id": "17525",
    "new_name": "Rayhan Sheikh",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "16-Nov-25",
    "remarks": ""
  },
  {
    "sl": 218,
    "replace_id": "17475",
    "replace_name": "Nizam Uddin Hawlader",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "9-Nov-25",
    "new_sl": "218",
    "new_id": "17524",
    "new_name": "Liton Chandra Howlader",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "16-Nov-25",
    "remarks": ""
  },
  {
    "sl": 219,
    "replace_id": "17307",
    "replace_name": "Emon Bepary",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "11-Oct-25",
    "new_sl": "219",
    "new_id": "17518",
    "new_name": "Kartik Das",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "15-Nov-25",
    "remarks": ""
  },
  {
    "sl": 220,
    "replace_id": "17418",
    "replace_name": "Lameya Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Lathe",
    "replace_doj": "1-Nov-25",
    "new_sl": "220",
    "new_id": "17486",
    "new_name": "Sumaya Akter Eva",
    "new_designation": "Helper",
    "new_section": "Fan Lathe",
    "new_doj": "10-Nov-25",
    "remarks": ""
  },
  {
    "sl": 221,
    "replace_id": "17476",
    "replace_name": "Nipa Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "0-Jan-00",
    "new_sl": "221",
    "new_id": "17481",
    "new_name": "Mst. Sonia Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "10-Nov-25",
    "remarks": ""
  },
  {
    "sl": 222,
    "replace_id": "17276",
    "replace_name": "Nasima Begum",
    "replace_designation": "Helper",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "11-Oct-25",
    "new_sl": "222",
    "new_id": "17480",
    "new_name": "Munni Akter",
    "new_designation": "Helper",
    "new_section": "Fan Armature Winding",
    "new_doj": "10-Nov-25",
    "remarks": ""
  },
  {
    "sl": 223,
    "replace_id": "16345",
    "replace_name": "Riya Moni",
    "replace_designation": "Quality Checker",
    "replace_section": "Fan QC",
    "replace_doj": "27-Oct-24",
    "new_sl": "223",
    "new_id": "17195",
    "new_name": "Baishakhai Akter Suborna",
    "new_designation": "Quality Checker",
    "new_section": "Fan QC",
    "new_doj": "28-Sep-25",
    "remarks": ""
  },
  {
    "sl": 224,
    "replace_id": "17160",
    "replace_name": "Md Firoz Alam nayem",
    "replace_designation": "Delivery Asst.",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "13-Sep-25",
    "new_sl": "224",
    "new_id": "17172",
    "new_name": "Md Yrasin Mirda",
    "new_designation": "Delivery Asst.",
    "new_section": "Fan Armature Winding",
    "new_doj": "15-Sep-25",
    "remarks": ""
  },
  {
    "sl": 225,
    "replace_id": "15314",
    "replace_name": "Ismail Khan Mitun",
    "replace_designation": "Delivery Asst.",
    "replace_section": "Fan Armature Winding",
    "replace_doj": "13-May-24",
    "new_sl": "225",
    "new_id": "17160",
    "new_name": "Md Firoz Alam nayem",
    "new_designation": "Delivery Asst.",
    "new_section": "Fan Armature Winding",
    "new_doj": "13-Sep-25",
    "remarks": ""
  },
  {
    "sl": 226,
    "replace_id": "62",
    "replace_name": "Sabita Rani Shil",
    "replace_designation": "HR Personnel",
    "replace_section": "Fan Admin",
    "replace_doj": "1-Jan-09",
    "new_sl": "226",
    "new_id": "16997",
    "new_name": "Md Nisad Islam",
    "new_designation": "HR Personnel",
    "new_section": "Fan Admin",
    "new_doj": "17-May-25",
    "remarks": ""
  },
  {
    "sl": 227,
    "replace_id": "15161",
    "replace_name": "Md Hiron",
    "replace_designation": "Quality Checker",
    "replace_section": "Fan QC",
    "replace_doj": "5-Mar-24",
    "new_sl": "227",
    "new_id": "16931",
    "new_name": "Polash Das",
    "new_designation": "Quality Checker",
    "new_section": "Fan QC",
    "new_doj": "16-Apr-25",
    "remarks": ""
  },
  {
    "sl": 228,
    "replace_id": "18838",
    "replace_name": "Md.Saidul Islam",
    "replace_designation": "Helper",
    "replace_section": "Fan Sada Shapla",
    "replace_doj": "03-Oct-2026",
    "new_sl": "228",
    "new_id": "19093",
    "new_name": "Niamul Islam",
    "new_designation": "Helper",
    "new_section": "Fan Sada Shapla",
    "new_doj": "03-Oct-2026",
    "remarks": "Resigned / ইস্তফা"
  },
  {
    "sl": 229,
    "replace_id": "18862",
    "replace_name": "Reshma Akter",
    "replace_designation": "Helper",
    "replace_section": "Fan Blade & Dimmer",
    "replace_doj": "03-Oct-2026",
    "new_sl": "229",
    "new_id": "19094",
    "new_name": "Sonia Akter",
    "new_designation": "Helper",
    "new_section": "Fan Blade & Dimmer",
    "new_doj": "03-Oct-2026",
    "remarks": "Resigned / ইস্তফা"
  }
];
